server:
  port: 8018

#mybatis配置
mybatis:
  type-aliases-package: com.ju.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
    #驼峰键值映射
    #configuration:
  #map-underscore-to-camel-case: on


#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xiaomusi520

#eureka 注册服务到哪里
eureka:
  client:
    service-url: #监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8018 #修改eureka中的默认描述信息

#info配置
info:
  app.name: ju-springcloud
  company.name: blog.ju.com