server:
  port: 9527
spring:
  application:
    name: spring-cloud-zuul
eureka:
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/

info:
  app.name: ju-springcloud
  company.name: www.justudy.com
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #不能再使用这个路径访问
  prefix: /ju
